name: fably
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  google_sign_in: ^5.2.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.0
  camera: ^0.10.5+9
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/google_logo.png

  fonts:
    - family: Italiana
      fonts:
        - asset: fonts/Italiana-Regular.ttf
    - family: Jura
      fonts:
        - asset: fonts/Jura-Regular.ttf
